const ACTION_TYPES = {
  //counterA
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  //toDo
  CREATE_TASK: "CREATE_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",
  //user
  CREATE_USER_REQUEST: "CREATE_USER_REQUEST",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_ERROR: "CREATE_USER_ERROR"
};

export default ACTION_TYPES;
